# 端口号
server:
  port: 8080

# datasource,数据连接
spring:
  datasource:
    #   driver-class-name: com.mysql.cj.jdbc.Driver
    #   基本属性
    #   url: jdbc:mysql://127.0.0.1/db_bill?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    #   username: root
    #   password: root123

    #  配置 druid 数据源
    druid:
      # JDBC配置
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/db_bill?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
      username: root
      password: root123
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      platform: mysql

      # 连接池配置
      # 配置初始化大小（默认0）、最小、最大（默认8）
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大。 默认为false
      pool-prepared-statements: true
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-open-prepared-statements: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小和最大生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000

      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。
      # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 1
      # 申请连接时执行validationQuery检测连接是否有效 默认为true
      test-on-borrow: true
      # 归还连接时执行validationQuery检测连接是否有效 默认为false
      test-on-return: false
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      filter:
        # 慢SQL记录(sql语句执行时间超过某个界限就记录下来)
        stat:
          slow-sql-millis: 200
          log-slow-sql: true

      # 监控配置
      # Druid WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.gif,*.png,*.jpg,*.html,*.js,*.css,*.ico
      # Druid StatViewServlet配置
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # 登录监控界面的用户名以及密码，登录url为localhost:8080/druid
        login-username: admin
        login-password: admin
        allow:
        deny:

# mybatis-plus
mybatis-plus:
  # 包扫描路径
  type-aliases-package: com.smp.bill.entity
  # Mapper 所对应的 XML 文件位置
  mapper-locations: classpath:mapping/*.xml
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局策略配置
  global-config:
    #  全局策略中的 DB 策略配置
    # 指定生成的主键的ID类型
    id-type: uuid
    # 表名、是否使用下划线命名，默认数据库表使用下划线命名
    table-underline: true
    # 逻辑已删除值(默认为 1)
    logic-delete-value: 1
    # 逻辑未删除值(默认为 0)
    logic-not-delete-value: 0

# pagehelper分页插件配置
pagehelper:
  helperDialect: postgresql #设置sql语言
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
